# ============================
# Skin metadata
# ============================

[skin]
name = "Demo Skinned Application"
author = "choneface"
version = "0.1"


# ============================
# Window definition
# ============================

[window]
width = 842
height = 1192
resizable = false


# ============================
# Assets
# ============================

[assets]
background = "images/background.png"
play_normal = "images/play_normal.png"
play_hover = "images/play_hover.png"
play_pressed = "images/play_pressed.png"


# ============================
# Parts / controls
# ============================

[[parts]]
id = "background"
type = "image"
asset = "background"
x = 0
y = 0
width = 842 
height = 1192
z = 0


[[parts]]
id = "play_button"
type = "button"
x = 16
y = 88
width = 23
height = 18
z = 10
action = "play"

[parts.draw]
normal = "play_normal"
hover = "play_hover"
pressed = "play_pressed"

[parts.hit]
type = "rect"
